### ISSUE TITLE
Tag logs with current Thread context information

### ISSUE THREAD

**Issue by Tonkpils** [reidmorrison/semantic_logger#10]
I would like to be able to tag logs with information retrieved from the context of the Thread that called the log method. Similar to how the `Thread.current_name` is appended but with custom information.

A use case for this would be tagging anything logged in a rack request context. For example, I use `Thread.current` to store a request's Id and it'd be useful to specify a configuration to ensure that request id gets tagged in all the logs. 

Right now this is possible if we wrap the log calls in the `tagged` method block and specify the request id. However, this is not possible in all instances. 

This is also not possible using custom formatters since these get run in the context of the appender Thread which wouldn't have the information we need.

**Comment by danielgatis** [comment]
> If you are running Rails you can add anything in the request into the logging tags, by setting `config.log_tags` in `application.rb`. For example:
> 
>     config.log_tags = [
>       :remote_ip,
>       -> request {request.cookie_jar['login'] || 'Not logged in'}
>     ]

@reidmorrison i'm bit confused here.

In the docs say the `config.log_tags` is a hash but in your example it is an array.
https://logger.rocketjob.io/rails.html

What is the correct way?
I did the hash approach but the log lines was generated very strange take a look:
```
2025-10-23 16:07:35.955029 D [10134:puma srv tp 001] [request_id] [request_id] [remote_ip] [remote_ip] [user_agent] [#<Proc:0x0000000111101870 <....>application.rb:71 (lambda)>] ActionView::Base --   Rendered admin/shared/_flash.html.erb (Duration: 0.7ms | Allocations: 236)
```
