### ISSUE TITLE
Rack::CommonLogger

### ISSUE THREAD

**Issue by amedeiros** [reidmorrison/semantic_logger#13]
Im working on a small sinatra application I wanted to switch out the Rack::CommonLogger with semantic logger so sinatra will log with semantic_logger. This does not seem possible, and I think its just semantic_logger missing some things to make it compatible but wanted to see if you could confirm

Example:
Required gems: sinatra, sinatra-contrib, semantic_logger

In this example the log statement in the main end point logs just fine. However, nothing from Rack::CommonLogger is making it into the log.
```ruby
require 'sinatra'
require 'sinatra/custom_logger'
require 'semantic_logger'

configure do
  register Sinatra::CustomLogger
  SemanticLogger.default_level = :info
  SemanticLogger.add_appender("#{settings.root}/log/#{settings.environment}.log", &SemanticLogger::Appender::Base.colorized_formatter)
  logger = SemanticLogger['TestLogger']
  set :raise_errors, true
  set :logger, logger
  use Rack::CommonLogger, logger
end

get '/' do
  # This makes it into the log file. But nothing from Rack::CommonLogger
  logger.warn("Test")
  'Logger testing'
end
```

In this example the log statement and the Rack::CommonLogger logs are making it into the log file which leads me to believe that semantic_logger is not compatible with Rack::CommonLogger

```ruby
require 'sinatra'
require 'sinatra/custom_logger'
require 'logger'

configure do
  register Sinatra::CustomLogger
  logger = Logger.new("#{settings.root}/log/#{settings.environment}.log")
  set :raise_errors, true
  set :logger, logger
  use Rack::CommonLogger, logger
end

get '/' do
  # This makes it into the log file and also from Rack::CommonLogger
  logger.warn("Test")
  'Logger testing'
end
```

The only difference between the two scenarios is one uses the logger class from ruby which is compatible with Rack::CommonLogger and the other is using SemanticLogger which does not seem compatible with Rack::CommonLogger.

Thanks!

**Comment by reidmorrison** [comment]
In the second scenario I get the following error:
```shell
Puma 2.8.2 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
== Sinatra (v1.4.6) has taken the stage on 4567 for development with backup from Puma
2015-07-22 21:55:01 -0400: Read error: #<NoMethodError: undefined method `write' for #<Logger:0x007fe3c13265c0>>
/Users/rmorrison/.rvm/gems/ruby-2.2.2@connect/gems/rack-1.5.5/lib/rack/commonlogger.rb:46:in `log'
```

With the first scenario I get a similar error. It appears we just need to map `#write` to for example `#info`. The following does the trick:
```ruby
require 'sinatra'
require 'sinatra/custom_logger'
require 'semantic_logger'

configure do
  register Sinatra::CustomLogger
  SemanticLogger.default_level = :info
  SemanticLogger.add_appender("test1.log", &SemanticLogger::Appender::Base.colorized_formatter)
  logger = SemanticLogger['TestLogger']

  # Send write calls to #info
  logger.instance_eval do
    def write(str)
      info(str)
    end
  end

  set :raise_errors, true
  set :logger, logger
  use Rack::CommonLogger, logger
end

get '/' do
  # This makes it into the log file. But nothing from Rack::CommonLogger
  logger.warn("Test")
  'Logger testing'
end
```

**Comment by amedeiros** [comment]
Ok thank you I will give that a try. I just really want to be able to use your logger its just much cleaner output and Im familiar with it.

**Comment by reidmorrison** [comment]
Going to close the issue for now, please re-open it if the info above did not help.

**Comment by deepak07** [comment]
Hi, 
I am facing similar issue. When I try to log in _development_ environment, everything is working fine. But when I started running the application in _QA_ environment nothing gets logged in the file. But when switched to Rack::CommonLogger requests are getting logged.

- I am using passenger using nginx to run the application

Anything that need to be done?

**Comment by reidmorrison** [comment]
Aside from doing the above, since you are using a forking framework and not using Rails Semantic Logger you also need add a callback to re-open log files after forking: https://rocketjob.github.io/semantic_logger/forking.html

**Comment by reidmorrison** [comment]
There is an opportunity for someone that uses Sinatra to create a `sinatra_semantic_logger` gem that does for Sinatra what the `rails_semantic_logger` gem does for Rails.

**Comment by deepak07** [comment]
I will make an effort to put out `sinatra_semantic_logger `. Let me check if I can come up with a solution.

**Comment by deepak07** [comment]
The issue was with forking. Adding semantic logger reload code on forking fixed it. Now logs are appearing. Thanks @reidmorrison  for pointing it out.
