### ISSUE TITLE
`sentry-raven` is deprecated! Please migrate to `sentry-ruby`

### ISSUE THREAD

**Issue by reidmorrison** [reidmorrison/semantic_logger#187]
Looking for help in migrating from gem `sentry-raven` to `sentry-ruby`, any takers?

**Comment by rewritten** [comment]
It's funny, I had a conversation with my coworkers about providing such a PR this same morning.

Count on me for some code soon enough, happy to help :)

**Comment by reidmorrison** [comment]
Merged PR. Will include it in the next minor release.
