### ISSUE TITLE
 Elasticsearch Specifying types in bulk requests is deprecated

### ISSUE THREAD

**Issue by xuwupeng2000** [reidmorrison/semantic_logger#225]
### Environment

Provide at least:
* Ruby Version: 3.1.2
* Semantic Logger Version: 4.11.0
* Application/framework names and versions: Rails 7.0.3
* Rails Semantic Logger Version:   rails_semantic_logger: 4.10.0

### Actual Behavior

> config.semantic_logger.add_appender(appender: :elasticsearch, url: "http://localhost:9200")

configure the logger to forward log to elasticsearch and get this in console:

> ^Cwarning: 299 Elasticsearch-7.14.2-6bc13727ce758c0e943c3c21653b3da82f627f75 "[types removal] Specifying types in bulk requests is deprecated."

Clearly, there is method used has been deprecated for ES7. 
ES7 doesn't support bulk requests with type.

**Comment by xuwupeng2000** [comment]
Just report this one to see if anyone has the same issue. I will come back and provide a fix.

**Comment by shaunbugler** [comment]
Yes this was raised in #167 but issue was closed, there is a work around but setting type must be removed if you want to use ES 8.X

**Comment by reidmorrison** [comment]
Anyone want to submit a Pull Request to fix the ES appender so that it is compatible with both the older and latest ES?

**Comment by reidmorrison** [comment]
New gem published with the merged PR.
