### ISSUE TITLE
Metrics section of the docs is out of date

### ISSUE THREAD

**Issue by kranzky** [reidmorrison/semantic_logger#283]
This was added in #35cb18c0 but the code was refactored in #e848e327. I'm guessing that the correct usage should now be:

```ruby
subscriber = SemanticLogger::Metric::NewRelic.new
```

instead of:

```ruby
subscriber = SemanticLogger::Metrics::NewRelic.new
```

This also means that https://logger.rocketjob.io/metrics.html is incorrect.

### Environment

* Ruby Version: **3.2.2**
* Semantic Logger Version: **4.15.0**
* Application/framework names and versions: **Rails and Sidekiq**
* Rails Semantic Logger Version: **4.14.0**

#### Rails Configuration

```ruby
on_worker_boot do
  ActiveRecord::Base.establish_connection
  SemanticLogger.reopen
  SemanticLogger.on_log(SemanticLogger::Metrics::NewRelic.new)
end
```

#### Full Stack Trace

```
[51] WARNING hook before_worker_boot failed with exception (NameError) uninitialized constant SemanticLogger::Metrics
```

### Expected Behavior

* Metrics are sent to newrelic

### Actual Behavior

* Metrics are not sent to newrelic

### Pull Request

#284

**Comment by reidmorrison** [comment]
Thank you for the pull request to fix the documentation.
