### ISSUE TITLE
Increasing the log level at runtime, globally or in just one class

### ISSUE THREAD

**Issue by yourtallness** [reidmorrison/semantic_logger#3]
The README mentions that semantic logger allows for changing the log level on a per class basis.

Could you provide an example of changing the log level:
- globally?
- in a specific class?

Thank you

**Comment by dan-corneanu** [comment]
This is an old post, however, I have a related question.
I would like to be able to set the log level for individual loggers, identified by their name, using environment variables. Something similar to `log4j`'s conventions. 
E.g. say I have two loggers named
* Refinitiv
* Refinitiv::RealTimeOrders
I would like to be able to set an env variable like `set LOG_LEVEL.refinitiv='debug'` and have both loggers use `debug` or add `set LOG_LEVEL.refinitiv.real_time_orders='trace'` and have one logger use `debug` and the other use `trace`.

Something like a hierarchical logging system.
What would be the easiest way to implement something like this?
